### ISSUE TITLE
Cut-Grade Slider

### ISSUE THREAD

**Issue by panigian** [btau/EleDiamond#1]
On quote-range view in the Quote Lookup, Tom wants a range slider with cut grades (excellent, very good, good, fair, poor) to give a more accurate quote range.

It might be better to make this optional and add it to the view with the rest of the categories.

**Comment by btau** [comment]
When I make the API request to Rap, they don’t take cut into consideration so the price they will send back will be the same regardless of the cut grade the user provides. 

Unless Will or Tom wants to put a value on each of those cuts?

i.e.: 
Excellent is 100% of rap
Very good is 90% of rap
etc...




http://technet.rapaport.com/Info/Prices/Format_Json.aspx <http://technet.rapaport.com/Info/Prices/Format_Json.aspx>


Get Price - sample request
{
"request": {
"header": {
"username": "awesome", 
"password": "jsonrocks"

}, 
"body":{
"shape": "round", 
"size": 2.10, 
"color": "E", 
"clarity": "VS2" 
}
}
}

**Comment by panigian** [comment]
yeah, he'd just give you percent values for each cut grade.

would it be better to have it on the last view then? Or or have it be optional and with the rest of the diamond specs.
